import { useAppStats } from './useAppStats';
import { useGitInfo } from './useGitInfo';
import { useWorkspaceCommands } from './useWorkspaceCommands';
import { useAppShortcutHandlers } from './useAppShortcutHandlers';
import { useAppWorkspaceModels } from './useAppWorkspaceModels';
import { useAppFocusRestore } from './useAppFocusRestore';
import { useAppUiActions } from './useAppUiActions';
import { useAppOverlayModels } from './useAppOverlayModels';
import { useAppLifecycleEffects } from './useAppLifecycleEffects';
import { useAppInteractionEffects } from './useAppInteractionEffects';
import { useAppStateBundle } from './useAppStateBundle';
import { useAppLayoutProps } from './useAppLayoutProps';

export function useAppRootModel() {
  const {
    loaded,
    setLoaded,
    store,
    setStore,
    sidebarWidth,
    setSidebarWidth,
    sidebarVisible,
    setSidebarVisible,
    appSettings,
    setAppSettings,
    metaKeyDown,
    setMetaKeyDown,
    workspace,
    workspaceActions,
    overlayState,
    toastState,
    paneActivity,
  } = useAppStateBundle();
  const {
    activeProjectId,
    activeTerminalId,
    panesByTerminalId,
    splitRootsByTerminalId,
    visitedTerminalIds,
    activePaneId,
    focusedPaneByTerminalId,
    maximizedTerminalId,
    sidebarFocusedTerminalId,
    paneCwds,
  } = workspace;
  const {
    setActiveProjectId,
    setPanesByTerminalId,
    setSplitRootsByTerminalId,
    setVisitedTerminalIds,
    setActivePaneId,
    setFocusedPaneByTerminalId,
    setMaximizedTerminalId,
    setSidebarFocusedTerminalId,
    selectTerminal,
    focusPane: focusPaneState,
    removeTerminalState,
    removeProjectState,
    rememberPaneCwd,
  } = workspaceActions;
  const { runningPaneIds, setRunningPaneIds, activityTerminalIds, setActivityTerminalIds, activityTerminalLastOutputAtById, activityNow } = paneActivity;
  const {
    dialog,
    setDialog,
    contextMenu,
    setContextMenu,
    pointerDragRef,
    resizingSidebarRef,
    justPointerDraggedRef,
    confirmClosePaneId,
    setConfirmClosePaneId,
    confirmDeleteProjectId,
    setConfirmDeleteProjectId,
    confirmDeleteTerminal,
    setConfirmDeleteTerminal,
    confirmQuitOpen,
    setConfirmQuitOpen,
    commandPaletteOpen,
    setCommandPaletteOpen,
    settingsOpen,
    setSettingsOpen,
    searchPaneRequest,
    setSearchPaneRequest,
    restartPaneRequest,
    setRestartPaneRequest,
  } = overlayState;
  const { toast, showToast } = toastState;

  const { activeProject, activeTerminal, sidebarTerminals, activePath, visitedTerminalWorkspaces } = useAppWorkspaceModels({
    store,
    activeProjectId,
    activeTerminalId,
    activePaneId,
    paneCwds,
    visitedTerminalIds,
    panesByTerminalId,
    splitRootsByTerminalId,
  });
  const appStats = useAppStats();
  const gitInfo = useGitInfo(activePath);
  const { restoreActivePaneFocus } = useAppFocusRestore(activePaneId);

  useAppLifecycleEffects({
    loaded,
    store,
    sidebarWidth,
    appSettings,
    setLoaded,
    setStore,
    setSidebarWidth,
    setAppSettings,
    selectTerminal,
    setActiveProjectId,
    activeProjectId,
    activeTerminalId,
    activePaneId,
    maximizedTerminalId,
    sidebarFocusedTerminalId,
    setConfirmQuitOpen,
    setContextMenu,
    rememberPaneCwd,
    showToast,
  });

  const commands = useWorkspaceCommands({
    store,
    setStore,
    dialog,
    setDialog,
    activeTerminal,
    activePaneId,
    focusedPaneByTerminalId,
    maximizedTerminalId,
    sidebarFocusedTerminalId,
    activeTerminalId,
    panesByTerminalId,
    splitRootsByTerminalId,
    sidebarTerminals,
    selectTerminal,
    focusPaneState,
    removeTerminalState,
    removeProjectState,
    setPanesByTerminalId,
    setSplitRootsByTerminalId,
    setActivePaneId,
    setFocusedPaneByTerminalId,
    setMaximizedTerminalId,
    setSidebarFocusedTerminalId,
    setRunningPaneIds,
    setActivityTerminalIds,
    requestPaneRestart: (paneId) => setRestartPaneRequest({ paneId, nonce: Date.now() }),
  });
  const {
    openProjectDialog,
    openTerminalDialog,
    submitDialog,
    toggleProject,
    openEditProjectDialog,
    openEditTerminalDialog,
    focusPane,
    deleteTerminal,
    moveProject,
    moveTerminal,
    deleteProject,
    splitPane,
    cyclePane,
    cycleSidebarTerminal,
    activateSidebarFocusedTerminal,
    activateTerminalByIndex,
    toggleMaximizedTerminal,
    resizeSplit,
    stopPane,
    restartPane,
    closePane,
  } = commands;

  useAppInteractionEffects({
    resizingSidebarRef,
    pointerDragRef,
    justPointerDraggedRef,
    setSidebarWidth,
    moveProject,
    moveTerminal,
    activeTerminal,
    focusedPaneByTerminalId,
    setVisitedTerminalIds,
    setPanesByTerminalId,
    setSplitRootsByTerminalId,
    setActivePaneId,
    setFocusedPaneByTerminalId,
  });

  const {
    adjustTerminalFontSize,
    openDirectoryInEditor,
    openPaneSearch,
    closeCommandPalette,
    closeContextMenu,
    closeSettings,
    closeDialog,
    submitActiveDialog,
  } = useAppUiActions({
    activePaneId,
    activePath,
    activeProjectPath: activeProject?.path,
    editorApp: appSettings.editor_app,
    setAppSettings,
    setSearchPaneRequest,
    setCommandPaletteOpen,
    setContextMenu,
    setSettingsOpen,
    setDialog,
    submitDialog,
    restoreActivePaneFocus,
    showToast,
  });

  const { commandPaletteItems } = useAppShortcutHandlers({
    store,
    sidebarTerminals,
    panesByTerminalId,
    activeProject,
    activeTerminal,
    activeTerminalId,
    activePaneId,
    activePath,
    appSettings,
    setMetaKeyDown,
    toggleSidebar: () => setSidebarVisible((visible) => !visible),
    setConfirmClosePaneId,
    setConfirmDeleteTerminal,
    setConfirmQuitOpen,
    setCommandPaletteOpen,
    setSettingsOpen,
    selectTerminal,
    openProjectDialog,
    openTerminalDialog,
    openEditProjectDialog,
    openEditTerminalDialog,
    deleteTerminal,
    splitPane,
    cycleSidebarTerminal,
    cyclePane,
    stopPane,
    restartPane,
    closePane,
    toggleMaximizedTerminal,
    activateTerminalByIndex,
    activateSidebarFocusedTerminal,
    adjustTerminalFontSize,
    openPaneSearch,
    openDirectoryInEditor,
  });

  const { confirmDeleteProject, confirmDeleteTerminalEntry } = useAppOverlayModels({ store, confirmDeleteProjectId, confirmDeleteTerminal });
  const layoutProps = useAppLayoutProps({
    sidebarVisible,
    sidebarWidth,
    store,
    activeProjectId,
    activeTerminalId,
    sidebarFocusedTerminalId,
    sidebarTerminals,
    runningPaneIds,
    activityTerminalIds,
    activityTerminalLastOutputAtById,
    activityNow,
    metaKeyDown,
    appStats,
    justPointerDraggedRef,
    pointerDragRef,
    resizingSidebarRef,
    toggleProject,
    selectTerminal,
    setContextMenu,
    openProjectDialog,
    openTerminalDialog,
    activePath,
    gitInfo,
    visitedTerminalWorkspaces,
    activePaneId,
    maximizedTerminalId,
    appSettings,
    searchPaneRequest,
    restartPaneRequest,
    resizeSplit,
    focusPane,
    closePane,
    setConfirmClosePaneId,
    toggleMaximizedTerminal,
    splitPane,
    toggleSidebar: () => setSidebarVisible((visible) => !visible),
    setAppSettings,
    contextMenu,
    commandPaletteOpen,
    commandPaletteItems,
    settingsOpen,
    dialog,
    confirmClosePaneId,
    confirmDeleteProject,
    confirmDeleteTerminal,
    confirmDeleteTerminalEntry,
    confirmQuitOpen,
    toast,
    setDialog,
    setConfirmDeleteProjectId,
    setConfirmDeleteTerminal,
    setConfirmQuitOpen,
    closeContextMenu,
    closeCommandPalette,
    closeSettings,
    closeDialog,
    submitActiveDialog,
    openEditProjectDialog,
    openEditTerminalDialog,
    deleteProject,
    deleteTerminal,
    restoreActivePaneFocus,
  });

  return layoutProps;
}
