import type { Dispatch, SetStateAction } from 'react';
import type { TerminalEntry, Project, Store, WorkspaceEntry } from '../types';
import type { ResolvedAppSettings } from '../settingsModel';

export type AppShortcutHandlerOptions = {
  store: Store;
  sidebarWorkspaces: { project: Project; terminal: WorkspaceEntry }[];
  terminalsByWorkspaceId: Record<string, TerminalEntry[]>;
  activeProject: Project | null;
  activeWorkspace: WorkspaceEntry | null;
  activeWorkspaceId: string | null;
  activeTerminalId: string | null;
  activePath: string | null;
  appSettings: ResolvedAppSettings;
  setMetaKeyDown: (down: boolean) => void;
  toggleSidebar: () => void;
  setConfirmCloseTerminalId: Dispatch<SetStateAction<string | null>>;
  setConfirmDeleteWorkspace: Dispatch<SetStateAction<{ projectId: string; workspaceId: string } | null>>;
  setConfirmQuitOpen: Dispatch<SetStateAction<boolean>>;
  setCommandPaletteOpen: Dispatch<SetStateAction<boolean>>;
  setSettingsOpen: Dispatch<SetStateAction<boolean>>;
  selectWorkspace: (projectId: string, workspaceId: string | null) => void;
  openProjectDialog: () => void;
  openWorkspaceDialog: (project: Project) => void;
  openEditProjectDialog: (project: Project) => void;
  openEditWorkspaceDialog: (project: Project, terminal: WorkspaceEntry) => void;
  deleteWorkspace: (projectId: string, workspaceId: string) => void;
  splitTerminal: (direction: 'row' | 'column', targetTerminalId?: string) => void;
  cycleSidebarWorkspace: (delta: number) => void;
  cycleTerminal: (delta: number) => void;
  stopTerminal: (terminalId: string) => void;
  restartTerminal: (terminalId: string) => void;
  closeTerminal: (terminalId: string) => void;
  toggleMaximizedTerminal: (terminalId?: string | null) => void;
  activateWorkspaceByIndex: (index: number) => void;
  activateSidebarFocusedWorkspace: () => void;
  adjustTerminalFontSize: (delta: number) => void;
  openTerminalSearch: () => void;
  openDirectoryInEditor: () => void;
};
