import type { Dispatch, SetStateAction } from 'react';
import type { Pane, Project, Store, TerminalEntry } from '../types';
import type { ResolvedAppSettings } from '../settingsModel';

export type AppShortcutHandlerOptions = {
  store: Store;
  sidebarTerminals: { project: Project; terminal: TerminalEntry }[];
  panesByTerminalId: Record<string, Pane[]>;
  activeProject: Project | null;
  activeTerminal: TerminalEntry | null;
  activeTerminalId: string | null;
  activePaneId: string | null;
  activePath: string | null;
  appSettings: ResolvedAppSettings;
  setMetaKeyDown: (down: boolean) => void;
  setConfirmClosePaneId: Dispatch<SetStateAction<string | null>>;
  setConfirmDeleteTerminal: Dispatch<SetStateAction<{ projectId: string; terminalId: string } | null>>;
  setConfirmQuitOpen: Dispatch<SetStateAction<boolean>>;
  setCommandPaletteOpen: Dispatch<SetStateAction<boolean>>;
  setSettingsOpen: Dispatch<SetStateAction<boolean>>;
  selectTerminal: (projectId: string, terminalId: string | null) => void;
  openProjectDialog: () => void;
  openTerminalDialog: (project: Project) => void;
  openEditProjectDialog: (project: Project) => void;
  openEditTerminalDialog: (project: Project, terminal: TerminalEntry) => void;
  deleteTerminal: (projectId: string, terminalId: string) => void;
  splitPane: (direction: 'row' | 'column', targetPaneId?: string) => void;
  cycleSidebarTerminal: (delta: number) => void;
  cyclePane: (delta: number) => void;
  stopPane: (paneId: string) => void;
  restartPane: (paneId: string) => void;
  closePane: (paneId: string) => void;
  toggleMaximizedTerminal: (paneId?: string | null) => void;
  activateTerminalByIndex: (index: number) => void;
  activateSidebarFocusedTerminal: () => void;
  adjustTerminalFontSize: (delta: number) => void;
  openPaneSearch: () => void;
  openDirectoryInEditor: () => void;
};
