// Generated by npm run kanban:contract:generate. Do not edit.
import type { SplitNode } from '../types';
import type { BoardSnapshot, BoardChange, CardSnapshot, CleanupPreflight, CardRuntimeCleanupResult, CardEnvironmentPane, CardEnvironmentIndicator, KanbanCardSummary, KanbanCardDetail, CleanupResource, RuntimeResourceOutcome, EnvironmentCreationOperation, CardCleanupOperation, CardEnvironment } from './types';

export type BoundaryEnvironmentLifecycle = 'creating' | 'ready' | 'cleanup_pending' | 'cleanup_failed';
export type BoundaryPiLifecycleIntent = 'agent_started' | 'agent_settled' | 'protocol_failed' | 'process_exited' | 'ui_input_requested' | 'ui_input_resolved';

// Rust CardEnvironment: id:String, card_id:String, project_id:String, worktree_path:String, branch:String, repository_id:Option<String>, target_checkout_path:Option<String>, target_branch:Option<String>, source_revision:Option<String>, target_revision:Option<String>, lifecycle_state:EnvironmentLifecycle, revision:i64, layout_revision:i64, split_layout:serde_json::Value, focused_pane_id:Option<String>, panes:Vec<CardPane>
export type BoundaryCardEnvironment = {
  id: string;
  card_id: string;
  project_id: string;
  worktree_path: string;
  branch: string;
  repository_id: string | null;
  target_checkout_path: string | null;
  target_branch: string | null;
  source_revision: string | null;
  target_revision: string | null;
  lifecycle_state: BoundaryEnvironmentLifecycle;
  revision: number;
  layout_revision: number;
  split_layout: SplitNode;
  focused_pane_id: string | null;
  panes: (CardEnvironmentPane)[];
};

// Rust EnvironmentCreationOperation: id:String, phase:String, error:Option<String>, source_path:Option<String>, source_branch:Option<String>, cleanup_available:bool, custom_command:bool, revision:i64
export type BoundaryEnvironmentCreationOperation = {
  id: string;
  phase: string;
  error: string | null;
  source_path: string | null;
  source_branch: string | null;
  cleanup_available: boolean;
  custom_command: boolean;
  revision: number;
};

// Rust CardCleanupOperation: status:String, phase:String, error_code:Option<String>, error_detail:Option<String>, started_at:i64, updated_at:i64, completed_at:Option<i64>
export type BoundaryCardCleanupOperation = {
  status: string;
  phase: string;
  error_code: string | null;
  error_detail: string | null;
  started_at: number;
  updated_at: number;
  completed_at: number | null;
};

// Rust KanbanCardSummary: id:String, provider:String, external_id:String, title:String, board_id:String, board_title:String, list_title:String, assignee_names:Vec<String>, status:CardStatus, completion_outcome:Option<CompletionOutcome>, workflow_revision:i64, record_revision:i64, project_id:Option<String>, parent:Option<CardRelationshipSummary>, child_count:u64, children:Vec<CardRelationshipSummary>, hierarchy_finalized:bool, environment:Option<CardEnvironmentIndicator>, pull_request:Option<CardPullRequestIndicator>, creation_operation:Option<CardCreationIndicator>, cleanup_operation:Option<CardCleanupIndicator>, runtime_cleanup_status:Option<String>, created_at:i64, updated_at:i64, sort_order:i64
export type BoundaryKanbanCardSummary = {
  id: string;
  record_revision: number;
  workflow_revision: number;
  environment: CardEnvironmentIndicator | null;
  creation_operation: Pick<EnvironmentCreationOperation, 'phase' | 'error'> | null;
  cleanup_operation: Pick<CardCleanupOperation, 'status'> | null;
};

// Rust KanbanCard: id:String, provider:String, external_id:String, title:String, content:String, board_id:String, board_title:String, list_id:String, list_title:String, card_url:String, assignee_names:Vec<String>, status:CardStatus, completion_outcome:Option<CompletionOutcome>, feature_environment:bool, pull_request:Option<CardPullRequest>, delivery_operation_stage:Option<String>, delivery_error:Option<String>, scripted_delivery:Option<ScriptedDeliveryOperation>, runtime_cleanup_status:Option<String>, runtime_cleanup_error:Option<String>, workflow_revision:i64, record_revision:i64, project_id:Option<String>, parent:Option<CardRelationshipSummary>, child_count:u64, children:Vec<CardRelationshipSummary>, hierarchy_finalized:bool, environment:Option<CardEnvironment>, creation_operation:Option<EnvironmentCreationOperation>, cleanup_operation:Option<CardCleanupOperation>, provider_sync:Option<provider_sync::ProviderSyncOperationSummary>, created_at:i64, updated_at:i64, sort_order:i64, in_scope:bool, events:Vec<CardEvent>, capabilities:Vec<WorkflowCapability>
export type BoundaryKanbanCard = {
  id: string;
  record_revision: number;
  workflow_revision: number;
  environment: CardEnvironment | null;
  creation_operation: EnvironmentCreationOperation | null;
  cleanup_operation: CardCleanupOperation | null;
};

// Rust BoardSnapshot: cards:Vec<KanbanCardSummary>, board_revision:i64
export type BoundaryBoardSnapshot = {
  cards: (KanbanCardSummary)[];
  board_revision: number;
};

// Rust BoardChange: upserts:Vec<KanbanCardSummary>, removed_ids:Vec<String>, detail_invalidated_ids:Vec<String>, board_revision:i64
export type BoundaryBoardChange = {
  upserts: (KanbanCardSummary)[];
  removed_ids: (string)[];
  detail_invalidated_ids: (string)[];
  board_revision: number;
};

// Rust CardSnapshot: card:KanbanCardDetail, board_revision:i64
export type BoundaryCardSnapshot = {
  card: KanbanCardDetail;
  board_revision: number;
};

// Rust CleanupPreflight: card_id:String, card_number:String, card_title:String, project_id:String, project_name:String, completion_outcome:String, workflow_revision:i64, environment_revision:i64, merged:bool, blocked:bool, override_available:bool, has_resources:bool, eligible:bool, state:String, repository_id:Option<String>, primary_checkout:Option<String>, recorded_target_branch:Option<String>, current_target_branch:Option<String>, target_revision:Option<String>, source_path:Option<String>, source_exists:bool, source_registered:bool, source_branch:Option<String>, source_clean:Option<bool>, source_head:Option<String>, source_revision:Option<String>, source_git_operation:Option<bool>, merge_proof:String, local_branch_disposition:String, remote_branch_disposition:String, resources:Vec<CleanupResource>, metadata:Vec<String>, blockers:Vec<String>, retained:Vec<String>, orphan_warning:Option<String>
export type BoundaryCleanupPreflight = {
  card_id: string;
  workflow_revision: number;
  environment_revision: number;
  state: string;
  repository_id: string | null;
  source_clean: boolean | null;
  resources: (CleanupResource)[];
  blockers: (string)[];
};

// Rust CardRuntimeCleanupResult: card:KanbanCard, outcomes:Vec<RuntimeResourceOutcome>
export type BoundaryCardRuntimeCleanupResult = {
  card: KanbanCardDetail;
  outcomes: (RuntimeResourceOutcome)[];
};
// Command kanban_cards(): Result<BoardSnapshot, String>
export type BoundaryRequest_kanban_cards = {  };
// Command kanban_card_snapshot(id: String): Result<CardSnapshot, String>
export type BoundaryRequest_kanban_card_snapshot = { id: string };
// Command kanban_cleanup_preflight(app: AppHandle, id: String): Result<CleanupPreflight, String>
export type BoundaryRequest_kanban_cleanup_preflight = { id: string };
// Command kanban_start_environment(state: State<'_, WorkspaceSetupState>, service: State<'_, SuperthreadService>, id: String, expected_workflow_revision: i64, setup_command: String, custom_command: bool, explicit_retry: Option<bool>,): Result<KanbanCard, String>
export type BoundaryRequest_kanban_start_environment = { id: string; expectedWorkflowRevision: number; setupCommand: string; customCommand: boolean; explicitRetry?: boolean };
// Command kanban_cleanup_environment_creation(id: String): Result<KanbanCard, String>
export type BoundaryRequest_kanban_cleanup_environment_creation = { id: string };
// Command kanban_apply_pi_lifecycle_intent(id: String, thread: PiThread, intent: PiLifecycleIntent, generation: String, event_id: String, event_order: Option<i64>, failure_detail: Option<String>,): Result<CardSnapshot, String>
export type BoundaryRequest_kanban_apply_pi_lifecycle_intent = { id: string; thread: 'planning' | 'work'; intent: BoundaryPiLifecycleIntent; generation: string; eventId: string; eventOrder?: number; failureDetail?: string };
// Command kanban_close_card(id: String, expected_revision: i64, pi_registry: State<'_, Mutex<PiRpcRegistry>>, pty_registry: State<'_, Mutex<PtyRegistry>>, service: State<'_, SuperthreadService>,): Result<CardRuntimeCleanupResult, String>
export type BoundaryRequest_kanban_close_card = { id: string; expectedRevision: number };
// Command kanban_retry_runtime_cleanup(id: String, pi_registry: State<'_, Mutex<PiRpcRegistry>>, pty_registry: State<'_, Mutex<PtyRegistry>>,): Result<CardRuntimeCleanupResult, String>
export type BoundaryRequest_kanban_retry_runtime_cleanup = { id: string };

type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
type Assert<T extends true> = T;
type CheckCardEnvironment = Assert<Equal<Required<Pick<CardEnvironment, keyof BoundaryCardEnvironment>>, BoundaryCardEnvironment>>;
type CheckEnvironmentCreationOperation = Assert<Required<Pick<EnvironmentCreationOperation, keyof BoundaryEnvironmentCreationOperation>> extends BoundaryEnvironmentCreationOperation ? true : false>;
type CheckCardCleanupOperation = Assert<Required<Pick<CardCleanupOperation, keyof BoundaryCardCleanupOperation>> extends BoundaryCardCleanupOperation ? true : false>;
type CheckKanbanCardSummary = Assert<Equal<Required<Pick<KanbanCardSummary, keyof BoundaryKanbanCardSummary>>, BoundaryKanbanCardSummary>>;
type CheckKanbanCard = Assert<Equal<Required<Pick<KanbanCardDetail, keyof BoundaryKanbanCard>>, BoundaryKanbanCard>>;
type CheckBoardSnapshot = Assert<Equal<Required<Pick<BoardSnapshot, keyof BoundaryBoardSnapshot>>, BoundaryBoardSnapshot>>;
type CheckBoardChange = Assert<Equal<Required<Pick<BoardChange, keyof BoundaryBoardChange>>, BoundaryBoardChange>>;
type CheckCardSnapshot = Assert<Equal<Required<Pick<CardSnapshot, keyof BoundaryCardSnapshot>>, BoundaryCardSnapshot>>;
type CheckCleanupPreflight = Assert<Required<Pick<CleanupPreflight, keyof BoundaryCleanupPreflight>> extends BoundaryCleanupPreflight ? true : false>;
type CheckCardRuntimeCleanupResult = Assert<Equal<Required<Pick<CardRuntimeCleanupResult, keyof BoundaryCardRuntimeCleanupResult>>, BoundaryCardRuntimeCleanupResult>>;
type CheckIntent = Assert<Equal<import('./types').PiLifecycleIntent, BoundaryPiLifecycleIntent>>;
